import React,{useEffect,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Activity,AlertTriangle,ArrowLeft,Binary,ChevronRight,Clock,Download,File,FileSearch,Globe2,Layers,Network,Radio,Search,ShieldCheck,Terminal,TimerReset,Trash2,X}from'lucide-react';
import{revisionChanged}from'./revision.js';
import{eventActor,mobilePanelClass,processEventsPath}from'./timeline.js';
import{eventIdChanges,eventIdsAfterBoundary,eventRowUpdateClasses,historyCountChanges,parentEventBoundaryChanges,processPidsForEventIds}from'./refresh-highlights.js';
import{baselineBoundary,parentsPath}from'./dashboard.js';
import{handleAuthRequired,loginWithPassword,sessionHeaders}from'./auth.js';
import'./styles.css';
sessionStorage.removeItem('igiris-token');
let authToken=sessionStorage.getItem('igiris-session')||'';
const clearSession=()=>{authToken='';sessionStorage.removeItem('igiris-session')};
const authHeaders=()=>sessionHeaders(authToken);
const authRequiredError=()=>Object.assign(new Error('AUTH_REQUIRED'),{code:'AUTH_REQUIRED'});
const api=async(path,opts={})=>{const r=await fetch(path,{...opts,headers:{...authHeaders(),...(opts.headers||{})}});if(r.status===401)throw authRequiredError();if(!r.ok)throw new Error(await r.text());return r.json()};
const download=async(path,name)=>{const r=await fetch(path,{headers:authHeaders()});if(r.status===401)throw authRequiredError();if(!r.ok)throw new Error(await r.text());const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
const ago=(value)=>{const s=Math.max(0,(Date.now()-new Date(value))/1000);return s<60?`${Math.floor(s)}s ago`:s<3600?`${Math.floor(s/60)}m ago`:s<86400?`${Math.floor(s/3600)}h ago`:`${Math.floor(s/86400)}d ago`};
const short=(v,n=18)=>v&&v.length>n?`${v.slice(0,n-1)}…`:v||'—';
const destination=e=>e.domain||e.raddr||'—';
function Badge({children,tone=''}){return <span className={`badge ${tone}`}>{children}</span>}
function CallSite({event}){
  const cs = event?.raw_meta?.call_site;
  if (!cs?.library) return null;
  const src = cs.call_site_source || cs.source || 'user_space_stack_v1.0';
  return <Badge tone="cyan">📍 Call Site: {cs.library} @ {cs.offset} <small>({src})</small></Badge>;
}
function App(){const[health,setHealth]=useState(null),[parents,setParents]=useState([]),[historyUpdates,setHistoryUpdates]=useState({}),[eventUpdates,setEventUpdates]=useState({}),[refreshEpoch,setRefreshEpoch]=useState(0),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[advancedMode,setAdvancedMode]=useState(false),[search,setSearch]=useState(''),[baseline,setBaseline]=useState(false),[mode,setMode]=useState('combined'),[dest,setDest]=useState(''),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[newData,setNewData]=useState(false),[error,setError]=useState(''),[authRequired,setAuthRequired]=useState(false),[passwordInput,setPasswordInput]=useState(''),[authError,setAuthError]=useState(''),[authBusy,setAuthBusy]=useState(false),[confirmClear,setConfirmClear]=useState(false),[clearing,setClearing]=useState(false),[notice,setNotice]=useState('');const loadedRevision=useRef(''),parentsSnapshot=useRef(null),detailSnapshot=useRef(null),pendingDetailBoundaries=useRef({}),highlightTimer=useRef(null),searchReady=useRef(false),searchRequest=useRef(0);
 const handleError=(e,onOther=message=>setError(message))=>{if(!handleAuthRequired(e,()=>{clearSession();setAuthRequired(true)}))onOther(e.message)};
 const applyParents=(next,highlight)=>{const changes=highlight?historyCountChanges(parentsSnapshot.current,next):{};if(highlight){const boundaries=parentEventBoundaryChanges(parentsSnapshot.current,next);for(const[root,boundary]of Object.entries(boundaries)){if(pendingDetailBoundaries.current[root]===undefined)pendingDetailBoundaries.current[root]=boundary}}parentsSnapshot.current=next;setParents(next);setHistoryUpdates(changes);return changes};
 const refresh=async({baselineOverride=baseline,highlightHistory=false}={})=>{try{setRefreshing(true);setError('');const before=await api('/api/revision');const[h,p]=await Promise.all([api('/api/health'),api(parentsPath(search,baselineOverride))]);setAuthRequired(false);setHealth(h);const parentChanges=applyParents(p,highlightHistory);let newEventIds=[];if(selected){try{const nextDetail=await api(`/api/parents/${selected}?mode=combined&baseline_only=${baselineOverride}`);newEventIds=highlightHistory?eventIdChanges(detailSnapshot.current?.events||null,nextDetail.events):[];detailSnapshot.current=nextDetail;setDetail(nextDetail);setEventUpdates(Object.fromEntries(newEventIds.map(id=>[id,true])));delete pendingDetailBoundaries.current[selected];if(highlightHistory)setRefreshEpoch(value=>value+1)}catch(e){if(e.code==='AUTH_REQUIRED')throw e;setSelected(null);setDetail(null);detailSnapshot.current=null;setEventUpdates({})}}else setEventUpdates({});if(highlightTimer.current)clearTimeout(highlightTimer.current);if(Object.keys(parentChanges).length||newEventIds.length)highlightTimer.current=setTimeout(()=>{setHistoryUpdates({});setEventUpdates({})},8000);const after=await api('/api/revision');loadedRevision.current=before.revision;setNewData(revisionChanged(before.revision,after.revision))}catch(e){handleError(e)}finally{setLoading(false);setRefreshing(false)}};
 useEffect(()=>{refresh()},[]);
 useEffect(()=>{if(!searchReady.current){searchReady.current=true;return}if(selected)return;const request=++searchRequest.current;const id=setTimeout(async()=>{setLoading(true);setError('');try{const next=await api(parentsPath(search,baseline));if(request!==searchRequest.current)return;applyParents(next,false)}catch(e){if(request!==searchRequest.current)return;handleError(e)}finally{if(request===searchRequest.current)setLoading(false)}},250);return()=>clearTimeout(id)},[search]);
 useEffect(()=>{const check=async()=>{try{const current=await api('/api/revision');if(revisionChanged(loadedRevision.current,current.revision))setNewData(true)}catch(e){handleError(e)}};const id=setInterval(check,3000);return()=>clearInterval(id)},[]);
 useEffect(()=>()=>{if(highlightTimer.current)clearTimeout(highlightTimer.current)},[]);
 const setMark=async()=>{const boundary=baselineBoundary(parents);if(!boundary){setError('No displayed evidence is available to baseline.');return}try{const result=await api('/api/baseline',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({baseline_ts:boundary})});setHealth(current=>({...current,baseline_ts:result.baseline_ts}));setBaseline(false);setError('')}catch(e){handleError(e)}};
 const clearMark=async()=>{try{await api('/api/baseline',{method:'DELETE'});setBaseline(false);refresh({baselineOverride:false})}catch(e){handleError(e)}};
 const changeBaseline=next=>{setBaseline(next);refresh({baselineOverride:next})};
 const clearEvidence=async()=>{try{setClearing(true);setError('');const result=await api('/api/evidence',{method:'DELETE'});const current=await api('/api/revision');loadedRevision.current=current.revision;applyParents([],false);setSelected(null);setDetail(null);detailSnapshot.current=null;pendingDetailBoundaries.current={};setEventUpdates({});setSearch('');setBaseline(false);setDest('');setNewData(false);setHealth(value=>({...value,baseline_ts:null}));setConfirmClear(false);setNotice(`Cleared ${result.cleared.events} network events, ${result.cleared.processes} process records, and ${result.cleared.artifacts} advanced artifacts. Fresh monitoring is active.`)}catch(e){handleError(e)}finally{setClearing(false)}};
 const open=async id=>{setSelected(id);setDest('');setMode('combined');setEventUpdates({});try{const nextDetail=await api(`/api/parents/${id}?mode=combined&baseline_only=${baseline}`);const boundary=pendingDetailBoundaries.current[id];const ids=boundary===undefined?[]:eventIdsAfterBoundary(nextDetail.events,boundary);delete pendingDetailBoundaries.current[id];detailSnapshot.current=nextDetail;setDetail(nextDetail);setEventUpdates(Object.fromEntries(ids.map(eventId=>[eventId,true])));if(ids.length){if(highlightTimer.current)clearTimeout(highlightTimer.current);highlightTimer.current=setTimeout(()=>{setHistoryUpdates({});setEventUpdates({})},8000)}}catch(e){handleError(e)}};
 const downloadEvidence=async(path,name)=>{try{await download(path,name)}catch(e){handleError(e)}};
 const unlock=async e=>{e.preventDefault();if(!passwordInput||authBusy)return;setAuthBusy(true);setAuthError('');try{const session=await loginWithPassword(passwordInput);authToken=session.token;sessionStorage.setItem('igiris-session',authToken);setPasswordInput('');setAuthRequired(false);await refresh()}catch(loginError){clearSession();setAuthRequired(true);setAuthError(loginError.message)}finally{setAuthBusy(false)}};
 return <div className="app">
  {authRequired&&<div className="auth-screen"><form onSubmit={unlock}><div className="mark"><ShieldCheck/></div><p className="eyebrow">SECURE LOCAL ACCESS</p><h2>Unlock Igiris</h2><p>Enter your local Igiris password.</p><input autoFocus type="password" autoComplete="current-password" value={passwordInput} onChange={e=>setPasswordInput(e.target.value)} placeholder="Password" aria-label="Igiris password"/>{authError&&<p className="auth-error" role="alert">{authError}</p>}<button type="submit" disabled={authBusy||!passwordInput}>{authBusy?'Unlocking…':'Unlock investigation'}</button></form></div>}
  <aside><div className="brand"><div className="mark"><Network size={20}/></div><div><strong>IGIRIS <span className="brand-version">{health?.version?`v${health.version}`:'v—'}</span></strong><small>PROCESS NETWORK INTELLIGENCE</small></div></div>
   <nav><button className="nav active"><Activity/>Investigation</button><button className="nav"><FileSearch/>Evidence</button></nav>
   <div className="side-foot"><span className={`pulse ${health?.visibility==='full'?'good':'warn'}`}/><div><b>{health?.mode||'Starting collector'}</b><small>{health?.visibility||'checking'} visibility</small></div></div>
  </aside>
  <main>
   <header><div>{selected&&<button className="icon" onClick={()=>{setSelected(null);setDetail(null);detailSnapshot.current=null;setEventUpdates({})}}><ArrowLeft/></button>}<div><p className="eyebrow">HOST INVESTIGATION</p><h1>{selected&&detail?detail.parent.name:'Network parents'}</h1></div></div><div className="header-actions"><div className="search"><Search/><input aria-label="Search" placeholder="Process, domain, IP, path, hash…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<X onClick={()=>setSearch('')}/>}</div><button className={`secondary refresh-button ${newData?'attention':''}`} disabled={refreshing} onClick={()=>refresh({highlightHistory:true})}><TimerReset className={refreshing?'spinning':''}/>{refreshing?'Refreshing…':'Refresh'}{newData&&<span className="notice-dot"/>}</button></div></header>
   {newData&&<div className="new-data" role="status" aria-live="polite"><div><Radio/><span><b>New data available</b><small>The backend has new network evidence. Your current view has not changed.</small></span></div><button onClick={()=>refresh({highlightHistory:true})} disabled={refreshing}>{refreshing?'Refreshing…':'Show new entries'}</button></div>}
   {health?.visibility!=='full'&&<div className="visibility"><AlertTriangle/><div><b>Limited visibility</b><span>{health?.messages?.join(' ')}</span></div></div>}
   {error&&<div className="error">{error}</div>}
   <section className={`toolbar ${selected?'detail-toolbar':''}`}><div className="toolbar-modes"><div className="segmented"><button className={!baseline?'on':''} onClick={()=>changeBaseline(false)}>All activity</button><button className={baseline?'on':''} onClick={()=>changeBaseline(true)}>Baseline / new</button></div><div className="segmented investigation-mode" aria-label="Investigation mode"><button className={!advancedMode?'on':''} onClick={()=>setAdvancedMode(false)}>Normal</button><button className={advancedMode?'on advanced-on':''} onClick={()=>setAdvancedMode(true)}><Binary/>Advanced</button></div></div><div className="baseline-actions">{health?.baseline_ts?<><span>Baseline {ago(health.baseline_ts)}</span><button onClick={clearMark}>Clear baseline</button></>:<button onClick={setMark}><Clock/>Baseline displayed entries</button>}<button className="danger-link" onClick={()=>{setConfirmClear(true);setNotice('')}}><Trash2/>Clear evidence</button></div></section>
   {notice&&<div className="success-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss"><X/></button></div>}
   {confirmClear&&<div className="clear-confirm" role="alertdialog" aria-modal="true" aria-labelledby="clear-title"><AlertTriangle/><div><b id="clear-title">Clear the complete evidence database?</b><span>This permanently removes all network events, process lineage, advanced artifacts, and the current baseline. Monitoring restarts immediately from an empty boundary.</span></div><div><button className="secondary" onClick={()=>setConfirmClear(false)} disabled={clearing}>Cancel</button><button className="danger-button" onClick={clearEvidence} disabled={clearing}><Trash2/>{clearing?'Clearing…':'Clear database'}</button></div></div>}
   {selected?<Detail data={detail} mode={mode} setMode={setMode} dest={dest} setDest={setDest} baseline={baseline} eventUpdates={eventUpdates} refreshEpoch={refreshEpoch} advancedMode={advancedMode} handleError={handleError} downloadEvidence={downloadEvidence}/>:<Parents rows={parents} historyUpdates={historyUpdates} loading={loading} open={open}/>}
  </main>
 </div>}
function Parents({rows,historyUpdates,loading,open}){return <section><div className="section-title"><div><h2>Investigation roots</h2><p>Meaningful parent processes with current or historical network activity</p></div><Badge tone="lime">{rows.length} roots</Badge></div>{loading?<div className="empty">Loading activity…</div>:!rows.length?<div className="empty"><Radio/><h3>No matching network activity</h3><p>Generate traffic or broaden the current filters.</p></div>:<div className="parent-grid">{rows.map(p=><button className="parent-card" key={p.root_pid} onClick={()=>open(p.root_pid)}><div className="card-top"><div className={`proc-icon ${p.odd_path?'danger':''}`}><Terminal/></div><div className="proc"><h3>{p.name}</h3><span>PID {p.pid} · {p.user||'unknown user'}</span></div>{p.odd_path&&<Badge tone="danger">ODD PATH</Badge>}<ChevronRight className="chev"/></div><code className={p.odd_path?'odd':''}>{p.exe_path||'path unavailable'}</code><div className="metrics"><div><b>{p.live_connection_count}</b><span>Live</span></div><div><b className={`history-count ${historyUpdates[p.root_pid]?'updated':''}`} title={historyUpdates[p.root_pid]?`History increased by ${historyUpdates[p.root_pid]}`:undefined} aria-label={historyUpdates[p.root_pid]?`${p.history_event_count} history events, increased by ${historyUpdates[p.root_pid]}`:undefined}>{p.history_event_count}{historyUpdates[p.root_pid]&&<em>+{historyUpdates[p.root_pid]}</em>}</b><span>History</span></div><div><b>{p.unique_destination_count}</b><span>Destinations</span></div><div><b>{ago(p.last_activity)}</b><span>Last active</span></div></div><div className="chips">{p.top_destinations.map(d=><span key={d}>{short(d,25)}</span>)}</div></button>)}</div>}</section>}
function Detail({data,mode,setMode,dest,setDest,baseline,eventUpdates,refreshEpoch,advancedMode,handleError,downloadEvidence}){
 const[selectedPid,setSelectedPid]=useState(null),[processEvents,setProcessEvents]=useState(null),[processEventUpdates,setProcessEventUpdates]=useState({}),[processLoading,setProcessLoading]=useState(false),[processError,setProcessError]=useState(''),[advancedData,setAdvancedData]=useState(null),[advancedLoading,setAdvancedLoading]=useState(false),[advancedError,setAdvancedError]=useState(''),[mobilePanel,setMobilePanel]=useState('tree');const processHighlightTimer=useRef(null);
 useEffect(()=>{setSelectedPid(null);setProcessEvents(null);setProcessEventUpdates({});setProcessError('');setAdvancedData(null);setAdvancedError('');setMobilePanel('tree')},[data?.parent.root_pid]);
 useEffect(()=>()=>{if(processHighlightTimer.current)clearTimeout(processHighlightTimer.current)},[]);
 useEffect(()=>{if(!refreshEpoch||selectedPid===null||!data)return;let active=true;const previous=processEvents;setProcessLoading(true);setProcessError('');api(processEventsPath(data.parent.root_pid,selectedPid,baseline)).then(next=>{if(!active)return;const ids=eventIdChanges(previous,next);setProcessEvents(next);setProcessEventUpdates(Object.fromEntries(ids.map(id=>[id,true])));if(processHighlightTimer.current)clearTimeout(processHighlightTimer.current);if(ids.length)processHighlightTimer.current=setTimeout(()=>setProcessEventUpdates({}),8000)}).catch(e=>{if(active)handleError(e,message=>{setProcessError(message);setProcessEvents([]);setProcessEventUpdates({})})}).finally(()=>{if(active)setProcessLoading(false)});return()=>{active=false}},[refreshEpoch]);
 useEffect(()=>{if(!advancedMode||selectedPid===null||!data){setAdvancedData(null);setAdvancedError('');return}let active=true;setAdvancedLoading(true);setAdvancedError('');api(`/api/parents/${data.parent.root_pid}/processes/${selectedPid}/advanced`).then(next=>{if(active)setAdvancedData(next)}).catch(e=>{if(active)handleError(e,message=>{setAdvancedError(message);setAdvancedData(null)})}).finally(()=>{if(active)setAdvancedLoading(false)});return()=>{active=false}},[advancedMode,selectedPid,data?.parent.root_pid,refreshEpoch]);
 useEffect(()=>{if(selectedPid!==null)setMobilePanel(advancedMode?'advanced':'timeline')},[advancedMode]);
 if(!data)return <div className="empty">Loading process evidence…</div>;
 const{parent,processes}=data,allEvents=data.events;
 const selectedProcess=processes.find(p=>p.pid===selectedPid)||null;
 const sourceEvents=selectedPid===null?allEvents:(processEvents||[]);
 const visibleEventUpdates=selectedPid===null?eventUpdates:processEventUpdates;
 const updatedProcessPids=new Set([
  ...processPidsForEventIds(allEvents,Object.keys(eventUpdates).map(Number)),
  ...processPidsForEventIds(processEvents||[],Object.keys(processEventUpdates).map(Number)),
 ]);
 const hasTreeUpdates=updatedProcessPids.size>0,hasTimelineUpdates=Object.keys(visibleEventUpdates).length>0;
 const chips=[...new Set(sourceEvents.map(destination).filter(x=>x!=='—'))];
 const events=sourceEvents.filter(e=>mode==='combined'||(mode==='live'?e.type==='live_socket':e.type!=='live_socket')).filter(e=>!dest||e.domain===dest||e.raddr===dest);
 const eventRowClasses=eventRowUpdateClasses(events,visibleEventUpdates);
 const selectProcess=async process=>{
  if(selectedPid===process.pid){setSelectedPid(null);setProcessEvents(null);setProcessEventUpdates({});setAdvancedData(null);setAdvancedError('');setDest('');setMobilePanel('tree');return}
  setSelectedPid(process.pid);setProcessEvents(null);setProcessEventUpdates({});setAdvancedData(null);setAdvancedError('');setProcessLoading(true);setProcessError('');setDest('');setMobilePanel(advancedMode?'advanced':'timeline');
  try{setProcessEvents(await api(processEventsPath(parent.root_pid,process.pid,baseline)))}catch(e){handleError(e,message=>{setProcessError(message);setProcessEvents([])})}finally{setProcessLoading(false)}
 };
 return <section className="detail-section">
  <div className="detail-head"><div className={`proc-icon large ${parent.odd_path?'danger':''}`}><Terminal/></div><div className="identity"><div><h2>{parent.name}</h2><Badge>PID {parent.pid}</Badge><Badge>{parent.user||'unknown'}</Badge></div><code className={parent.odd_path?'odd':''}>{parent.exe_path||'path unavailable'}</code><div className="hash"><ShieldCheck/>SHA-256 <code>{parent.exe_hash||'hash unavailable'}</code></div></div><div className="detail-metrics"><b>{parent.history_event_count}</b><span>historical events</span><b>{parent.unique_destination_count}</b><span>unique destinations</span></div></div>
  <div className="actionbar"><div className="segmented">{['live','history','combined'].map(m=><button className={mode===m?'on':''} onClick={()=>setMode(m)} key={m}>{m[0].toUpperCase()+m.slice(1)}</button>)}</div><div><button className="secondary" onClick={()=>downloadEvidence(`/api/export.json?root_pid=${parent.root_pid}&baseline_only=${baseline}&mode=${mode}${dest?`&destination=${encodeURIComponent(dest)}`:''}`,'igiris-evidence.json')}><Download/>JSON</button><button className="secondary" onClick={()=>downloadEvidence(`/api/export.csv?root_pid=${parent.root_pid}&baseline_only=${baseline}&mode=${mode}${dest?`&destination=${encodeURIComponent(dest)}`:''}`,'igiris-evidence.csv')}><Download/>CSV</button></div></div>
  <div className="chipbar"><button className={!dest?'active':''} onClick={()=>setDest('')}>All destinations</button>{chips.map(c=><button className={dest===c?'active':''} onClick={()=>setDest(c)} key={c}>{c}</button>)}</div>
  <div className={`mobile-panel-switch ${advancedMode?'advanced-tabs':''}`} role="tablist" aria-label="Investigation detail view"><button className={`${mobilePanel==='tree'?'on':''} ${hasTreeUpdates?'updated':''}`} onClick={()=>setMobilePanel('tree')} role="tab" aria-selected={mobilePanel==='tree'}>Process tree <span>{processes.length}</span></button><button className={`${mobilePanel==='timeline'?'on':''} ${hasTimelineUpdates?'updated':''}`} onClick={()=>setMobilePanel('timeline')} role="tab" aria-selected={mobilePanel==='timeline'}>Event timeline <span>{events.length}</span></button>{advancedMode&&<button className={mobilePanel==='advanced'?'on advanced-on':''} onClick={()=>setMobilePanel('advanced')} role="tab" aria-selected={mobilePanel==='advanced'}>Advanced <span>{selectedPid===null?'—':'IOC'}</span></button>}</div>
  <div className="detail-grid">
   <div className={mobilePanelClass('tree',mobilePanel)}><div className="panel-title"><div><h3>Process tree</h3><small>Select a process to load all of its evidence</small></div><Badge>{processes.length} nodes</Badge></div>{processes.map(p=>{const windowCount=allEvents.filter(e=>e.pid===p.pid).length,count=selectedPid===p.pid&&processEvents?processEvents.length:windowCount;return <button className={`tree-node ${selectedPid===p.pid?'selected':''} ${updatedProcessPids.has(p.pid)?'updated':''}`} key={p.pid} onClick={()=>selectProcess(p)} aria-pressed={selectedPid===p.pid} aria-label={updatedProcessPids.has(p.pid)?`${p.name}, PID ${p.pid}, received new evidence on refresh`:undefined}><span className="branch">{p.pid===parent.root_pid?'◆':'└'}</span><div><b>{p.name}</b><small>PID {p.pid} · PPID {p.ppid}</small><code>{p.exe_path||'path unavailable'}</code></div><Badge tone={count?'lime':''}>{selectedPid===p.pid&&processLoading?'…':count}</Badge></button>})}</div>
   <div className={mobilePanelClass('timeline',mobilePanel)}><div className="panel-title"><div><h3>{selectedProcess?`${selectedProcess.name} events`:'Event timeline'}</h3><small>{selectedProcess?`PID ${selectedProcess.pid} · complete process history`:'Newest events across this investigation root'}</small></div><div className="panel-title-actions">{selectedProcess&&<button onClick={()=>{setSelectedPid(null);setProcessEvents(null);setProcessEventUpdates({});setAdvancedData(null);setDest('');setMobilePanel('tree')}}>Show all</button>}<Badge>{events.length} events</Badge></div></div>{processError&&<div className="error inline">{processError}</div>}{processLoading?<div className="empty small">Loading process events…</div>:!events.length?<div className="empty small">No events in this view.</div>:events.map((e,i)=>{const actor=eventActor(e,processes),rowUpdated=eventRowClasses[i]==='updated';return <div className={`event ${rowUpdated?'updated':''}`} key={e.id||i} aria-label={rowUpdated?'New event loaded by refresh':undefined}><div className={`event-dot ${e.type}`}/><div className="event-main"><div><Badge tone={e.type==='exec_network_tool'?'purple':e.type==='icmp'?'amber':''}>{e.type}</Badge>{rowUpdated&&<span className="new-event">NEW</span>}<CallSite event={e}/><b>{destination(e)}</b>{e.domain&&e.raddr&&<small>{e.raddr}</small>}</div><span className="event-actor"><Terminal/><strong>{actor.name}</strong><code>PID {actor.pid}</code></span></div><div className="event-meta"><code>{e.family.replace('ipv','v')} · {e.protocol||'—'}{e.rport?`/${e.rport}`:''}</code><span>{new Date(e.ts).toLocaleString()}</span></div></div>})}</div>
   {advancedMode&&<AdvancedEvidence className={`${mobilePanelClass('advanced',mobilePanel)} advanced-panel`} selectedProcess={selectedProcess} data={advancedData} loading={advancedLoading} error={advancedError}/>}
  </div>
 </section>
}
function AdvancedEvidence({className,selectedProcess,data,loading,error}){
 return <div className={className} aria-label="Advanced process evidence">
  <div className="panel-title advanced-title"><div><h3><Binary/>Advanced investigation</h3><small>Process-scoped IOC, execution, file, library, and network evidence</small></div>{data&&<Badge tone={data.collector.ebpf_available?'lime':'amber'}>{data.collector.mode||'collector'}</Badge>}</div>
  {!selectedProcess?<div className="advanced-empty"><Binary/><h3>Select a subprocess</h3><p>Choose any Process Tree entry to inspect its execution lineage, hashes, loaded libraries, observed files, and domain/IP network evidence.</p></div>:loading?<div className="empty small">Loading advanced process evidence…</div>:error?<div className="error inline">{error}</div>:data&&<>
   <div className="evidence-warning"><AlertTriangle/><span><b>{data.evidence_semantics.file_visibility.replace('_',' ')}</b>{data.evidence_semantics.warning}</span></div>
   <div className="ioc-grid"><div><span>Process</span><b>{data.process.name} · PID {data.process.pid}</b></div><div><span>Parent PID</span><code>{data.process.ppid}</code></div><div><span>User</span><b>{data.process.user||'unknown'}</b></div><div className="wide"><span>Executable</span><code>{data.process.exe_path||'unavailable'}</code></div><div className="wide"><span>SHA-256</span><code>{data.process.exe_hash||'unavailable'}</code></div><div className="wide"><span>Command line</span><code>{data.process.cmdline||data.process.name}</code></div></div>
   <div className="advanced-columns">
    <section className="evidence-block"><h4><Terminal/>Command execution <Badge>{data.commands.length}</Badge></h4>{!data.commands.length?<p className="evidence-empty">No observed command lineage.</p>:data.commands.map(command=><div className="command-row" key={command.pid}><span><b>{command.name}</b><small>PID {command.pid} · PPID {command.ppid}</small></span><code>{command.cmdline||command.exe_path||'command unavailable'}</code></div>)}</section>
    <section className="evidence-block"><h4><Layers/>Loaded libraries <Badge>{data.libraries.length}</Badge></h4>{!data.libraries.length?<p className="evidence-empty">No library mappings captured.</p>:<div className="path-list">{data.libraries.map(item=><LibraryEvidence item={item} key={item.id||item.path}/>)}</div>}</section>
    <section className="evidence-block"><h4><File/>Observed files <Badge>{data.files.length}</Badge></h4>{!data.files.length?<p className="evidence-empty">No open file descriptors captured.</p>:<div className="path-list">{data.files.map(item=><code key={item.id||item.path}>{item.path}</code>)}</div>}</section>
    <section className="evidence-block network-evidence"><h4><Globe2/>Network requests <Badge tone="lime">{data.network.length}</Badge></h4>{!data.network.length?<p className="evidence-empty">No network evidence for this process.</p>:<div className="network-table"><div className="network-head"><span>Domain</span><span>IP address</span><span>Transport</span><span>Observed</span></div>{data.network.map((event,index)=><div className="network-row" key={event.id||index}><code>{event.domain||'—'}</code><code>{event.raddr||'—'}</code><span>{event.protocol||'—'}{event.rport?`/${event.rport}`:''}<small>{event.domain_source}</small></span><time>{new Date(event.ts).toLocaleString()}</time><CallSite event={event}/></div>)}</div>}</section>
   </div>
  </>}
 </div>
}
function LibraryEvidence({item}){
 const traces=item.stack_traces||[],offsets=[...new Set(traces.flatMap(trace=>trace.attributed_frames||[]).map(frame=>frame.offset))];
 return <details className={item.network_related?'network-related-library library-evidence':'library-evidence'}>
  <summary><code>{item.path}</code>{offsets.map(offset=><span className="library-offset" key={offset}>+{offset}</span>)}{item.network_related&&<span className="library-network-marker">NETWORK</span>}</summary>
  {item.network_related&&!traces.length&&<small className="stack-unavailable">Network-correlated open; no captured stack frame matched this library.</small>}
  {traces.map((trace,index)=><div className="stack-trace" key={trace.event_id||index}>
   <small>{trace.domain||trace.raddr||'network event'}{trace.rport?`:${trace.rport}`:''} · {new Date(trace.ts).toLocaleString()}</small>
   <ol>{trace.frames.map((frame,frameIndex)=><li className={(trace.attributed_frames||[]).some(match=>match.raw_ip===frame.raw_ip)?'attributed-frame':''} key={`${frame.raw_ip}-${frameIndex}`}><code>{frame.library||'unresolved'}{frame.symbol?`!${frame.symbol}`:''} +{frame.offset} <span>{frame.raw_ip}</span></code></li>)}</ol>
  </div>)}
 </details>
}
createRoot(document.getElementById('root')).render(<App/>);
